{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a224e87-7e14-4918-b898-3871eeeb6f9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Functions to perform joint driftXpress\n",
    "def select_landmarks(y_pos, num_landmarks=128):\n",
    "    num_landmarks = min(num_landmarks, y_pos.shape[0])\n",
    "    indices = torch.randperm(y_pos.shape[0], device=y_pos.device)[:num_landmarks]\n",
    "    return y_pos[indices]\n",
    "\n",
    "def kzu(z, landmarks, T):\n",
    "    return torch.exp(-torch.cdist(z, landmarks) / T)\n",
    "\n",
    "def build_nystrom_cache(landmarks, T, jitter=1e-5):\n",
    "    K_uu = kzu(landmarks, landmarks, T)\n",
    "    K_uu = K_uu + jitter * torch.eye(len(landmarks), device=landmarks.device)\n",
    "    eigenvalues, eigenvectors = torch.linalg.eigh(K_uu)\n",
    "    eigenvalues = torch.clamp(eigenvalues, min=jitter)\n",
    "    return eigenvectors @ torch.diag(torch.rsqrt(eigenvalues)) @ eigenvectors.T\n",
    "\n",
    "def nystrom_map(z, landmarks, K_uu_inv_sqrt, T):\n",
    "    # The factor is cached: no eigendecomposition occurs during training.\n",
    "    return (kzu(z, landmarks, T) @ K_uu_inv_sqrt).T\n",
    "\n",
    "def pre_compute_summaries(y_pos, landmarks, K_uu_inv_sqrt, T):\n",
    "    phi_y = nystrom_map(y_pos, landmarks, K_uu_inv_sqrt, T)\n",
    "    return phi_y @ y_pos, phi_y.sum(dim=1, keepdim=True)\n",
    "\n",
    "def attraction(y_neg, landmarks, K_uu_inv_sqrt, Ap, bp, T):\n",
    "    phi = nystrom_map(y_neg, landmarks, K_uu_inv_sqrt, T)\n",
    "    numerator = (Ap.T @ phi).T\n",
    "    denominator = phi.T @ bp + 1e-8\n",
    "    return numerator / denominator\n",
    "\n",
    "\n",
    "def repulsion(y_neg, T):\n",
    "    N = y_neg.shape[0]\n",
    "    dist_neg = torch.cdist(y_neg, y_neg)\n",
    "    \n",
    "    # Remove self-interaction (Line 14)\n",
    "    dist_neg += torch.eye(N, device=dist_neg.device) * 1e6 \n",
    "    \n",
    "    K = torch.exp(-dist_neg / T)\n",
    "    \n",
    "    # Line 15 normalization\n",
    "    denominator = K.sum(dim=1, keepdim=True) + 1e-8\n",
    "    drift_neg = (K @ y_neg) / denominator\n",
    "    \n",
    "    return drift_neg\n",
    "\n",
    "def compute_V(y_neg, landmarks, K_uu_inv_sqrt, Ap, bp, T=1.0):\n",
    "    V_pos = attraction(y_neg, landmarks, K_uu_inv_sqrt, Ap, bp, T)\n",
    "    V_neg = repulsion(y_neg, T)\n",
    "    V = V_pos - V_neg\n",
    "    return V\n",
    "\n",
    "\n",
    "def drift_loss(generated, landmarks, K_uu_inv_sqrt, Ap, bp, T):\n",
    "    with torch.no_grad():\n",
    "        # y_neg is your generated batch\n",
    "        V = compute_V(generated, landmarks, K_uu_inv_sqrt, Ap, bp, T)\n",
    "        # Eq. (5) in the paper: regress to one full stop-gradient drift step.\n",
    "        frozen_targets = (generated + V).detach()\n",
    "    return mse(generated, frozen_targets), V\n",
    "\n",
    "def recon_loss(y_pos_recon, y_pos):\n",
    "    return F.mse_loss(y_pos_recon, y_pos, reduction='mean')\n",
    "\n",
    "\n",
    "def kl_loss(mu, logvar): # normalized\n",
    "    kl_per_sample = -0.5 * (\n",
    "        1 + logvar - mu.pow(2) - logvar.exp()\n",
    "    ).sum(dim=-1)\n",
    "\n",
    "    return kl_per_sample.mean()\n",
    "\n",
    "\n",
    "# see VICReg\n",
    "def variance_loss(mu, gamma=1.5, eps=1e-4):\n",
    "    std = torch.sqrt(mu.var(dim=0, unbiased=True) + eps)\n",
    "    return torch.mean(F.relu(gamma - std))\n",
    "\n",
    "def covariance_loss(latents):\n",
    "    batch_size, dim = latents.shape\n",
    "    latents = latents - latents.mean(dim=0, keepdim=True)\n",
    "    cov = (latents.T @ latents) / (batch_size - 1)   # bug fix: was `@ z`\n",
    "    off_diag = cov - torch.diag(torch.diag(cov))\n",
    "    return off_diag.pow(2).sum() / dim\n",
    "\n",
    "def total_loss(y_pos_recon, y_pos, y_pos_mu, y_pos_logvar, y_neg_latent, y_pos_latent, temp,\n",
    "                landmarks, K_uu_inv_sqrt, Ap, bp,\n",
    "                lambda_kl=0.01, lambda_drift=1.0, lambda_var=0.1, lambda_cov=0.1):\n",
    "    L_recon = recon_loss(y_pos_recon, y_pos)\n",
    "    L_kl    = kl_loss(y_pos_mu, y_pos_logvar)\n",
    "    L_drift, V = drift_loss(y_neg_latent, landmarks, K_uu_inv_sqrt, Ap, bp, temp)\n",
    "    L_var   = variance_loss(y_pos_mu) + variance_loss(y_neg_latent)\n",
    "    L_cov = covariance_loss(y_pos_mu) + covariance_loss(y_neg_latent)\n",
    "    total = L_recon + lambda_kl*L_kl + lambda_drift*L_drift + lambda_var*L_var + lambda_cov*L_cov\n",
    "    loss_items = {\"recon\": L_recon.detach(), \"kl\": L_kl.detach(),\n",
    "                    \"drift\": L_drift.detach(), \"V\": V.detach(),\"var\": L_var.detach(), \"covar\":L_cov.detach()}\n",
    "    return total, loss_items"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
